### ISSUE TITLE
Rearrange Detail View Column Order

### ISSUE THREAD

**Issue by aidan-gibson** [pls-rs/pls#103]
## Description

I would like control over horizontal order of the detail view columns. ie, if I do `pls --det 'user' --det 'group'`, I get user column then group column, but if I do `pls --det 'group' --det 'user'` I get group leftmost then user. Specific syntax doesn't matter to me, but you get the idea. 

## Alternatives

None of the competing programs (eza, lsd, etc) have the ability to do this and it's driven me crazy for years. This would be a significant differentiator.

**Comment by dhruvkb** [comment]
I just released [v0.0.1-beta.7](https://github.com/pls-rs/pls/releases/tag/v0.0.1-beta.7) which contains this feature.
