### ISSUE TITLE
pls core dumps with --down=true in a specific directory.

### ISSUE THREAD

**Issue by pulumiup** [pls-rs/pls#110]
## Description

Core dump while trying to list files with `pls -I=1 --grid=true --down=true'` in a folder that should contain 1–2 videos.  Core utils works fine.

## Expectations

To display the files without the core dump.

## Reproduction

Removing --down=true stops the error.

## Environment

zsh 5.9 (x86_64-pc-linux-gnu)
wezterm 20240203-110809-5046fc22

Cool autumn night? :)

**`pls` specifications:**

 pls 0.0.1-beta.7

Device specifications:

- Operating system: Nixos
- Version NixOS 24.11 (Vicuna)
- Other info: Unstable 

Flake.lock

```
      "locked": {
        "lastModified": 1726755586,
        "narHash": "sha256-PmUr/2GQGvFTIJ6/Tvsins7Q43KTMvMFhvG6oaYK+Wk=",
        "owner": "NixOS",
        "repo": "nixpkgs",
        "rev": "c04d5652cfa9742b1d519688f65d1bbccea9eb7e",
        "type": "github"
}
```

## Additional information

```
RUST_BACKTRACE=1 ls
thread 'main' panicked at src/output/grid.rs:76:43:
chunk size must be non-zero
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: pls::args::group::Group::render
   3: pls::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[1]    1502277 IOT instruction (core dumped)  RUST_BACKTRACE=1  -I=1 --grid=true --down=true
```

I suck at using GDB, not sure if I even did this right, maybe it will help?
```
Starting program: /nix/store/hfrjv0341bs8isy4rlwwlj7n5586rsdy-pls-0.0.1-beta.7/bin/pls pls -I=1 --grid=true --down=true
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/3dyw8dzj9ab4m8hv5dpyx7zii8d0w6fi-glibc-2.39-52/lib/libthread_db.so.1".
pls:
        error: No such file or directory (os error 2)
[Inferior 1 (process 1514845) exited normally]
```

Thank you!

**Comment by pulumiup** [comment]
Small adjustment appears to be doing it in any empty directory. Maybe I'm just miss understanding how the options are being used?

**Comment by dhruvkb** [comment]
Thanks for reporting! This was indeed a bug, it should be fixed in commit https://github.com/pls-rs/pls/commit/e65b259f1e9220cb40e347e938648c21ace40cc4. I'll cut a new release soon, alongside another fix.

**Comment by dhruvkb** [comment]
[Release v0.0.1-beta.8](https://github.com/pls-rs/pls/releases/tag/v0.0.1-beta.8) should fix this for empty directories. Please let me know if it still crashes in that folder with 1-2 videos.

**Comment by pulumiup** [comment]
Thank you for the quick fix! Seems to be fine, I just compiled from git.
