### ISSUE TITLE
Missing configuration documentation

### ISSUE THREAD

**Issue by acbuie** [pls-rs/pls#89]
## Description

Currently, there is not much documentation about the configuration file options, especially the `app_const` and `entry_const` options. Having a single page documenting all the options in the `.pls.yaml` file would be extremely helpful. 

In that vein, the link to https://pls-rs.github.io/pls/guides/conf/ is broken. The page does not exist, and results in an Error 404. It is linked from https://pls-rs.github.io/pls/guides/specs/#configuration. 

I have omitted the other sections in the issue template as they do not pertain to this bug/issue.

**Comment by dhruvkb** [comment]
Thank you for the report @acbuie. I will try to look into it asap. If you're interesting in writing some docs, let me know and feel free to open a PR!

**Comment by acbuie** [comment]
Thanks! I am happy to take a look and see what I can do. I am not too familiar with rust (yet), so it may take me a little while to get familiar with the repository.

**Comment by dhruvkb** [comment]
The docs site is JavaScript, and the content is Markdown, defined in https://github.com/pls-rs/pls/tree/main/docs/src/content/docs. Feel free to take your time, I might not be able to get around to this till the weekend.

**Comment by dhruvkb** [comment]
Hey @acbuie I've just pushed the docs with the schema for the `.pls.yml` configuration files. Being more of a reference than a guide, it's available at the URL https://pls-rs.github.io/pls/reference/conf/ and I've updated all mentions of the previous URL to point here instead. Thanks for reporting!
