### ISSUE TITLE
Error when no results

### ISSUE THREAD

**Issue by alewandows** [pls-rs/pls#94]
## Description

When running pls with -d option (detailed view) and when there are no results (empty directory, or no files matching the regex), I get the following error :

```
thread 'main' panicked at src/output/table.rs:76:29:
range end index 1 out of range for slice of length 0
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fish: Job 1, 'pls -d std --only="^\."' terminated by signal SIGABRT (Abort)
```

## Environment

**`pls` specifications:**

- Version: 0.0.1-beta.4

Device specifications:

- Operating system: macOS
- Version: 14.1
- Other info: fish shell

**Comment by dhruvkb** [comment]
I pushed a fix for this in 220598e, which is part of the new release https://github.com/pls-rs/pls/releases/tag/v0.0.1-beta.5.
