### ISSUE TITLE
Update comparison of alternatives

### ISSUE THREAD

**Issue by ccoVeille** [pls-rs/pls#98]
## Problem

https://github.com/pls-rs/pls/blob/main/docs%2Fsrc%2Fcontent%2Fdocs%2Fabout%2Fcomparison.mdx this file is somehow outdated

## Description

exa is no longer maintained, [eza](https://github.com/eza-community/eza) was created.

**Comment by dhruvkb** [comment]
Thanks for pointing that out, I've updated the docs to point to eza in commit d641847. The changes should be live soon!

**Comment by ccoVeille** [comment]
Thanks
